### ISSUE TITLE
Theme UI v1 Roadmap

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#832]
This is an umbrella issue for features and additions to bring Theme UI to a stable v1. This list may not be exhaustive and is subject to change. More details, context, and additional issues will be added where needed.

- [ ] TypeScript conversion #668
- [ ] TypeScript: Strict-mode theme interface/schema: a fully fleshed out theme schema to improve interoperability.
- [ ] TypeScript: Type check property values against theme scales
- [ ] Variant composition, e.g. `variant: ['large', 'primary']` (or plural `variants`). This would potentially be a breaking change, meaning that the `variant` property itself would no longer support responsive arrays, but the values within the variant could. #586
- [ ] Babel plugin for JSX pragma #479
- [ ] Upgrade to Emotion 11 https://github.com/emotion-js/emotion/issues/1606
- [ ] Use Theme UI context instead of Emotion context
- [ ] Remove "default" theme – remove default `fontSizes` and `space` values
- [ ] `gatsby-plugin-theme-ui`: support configuration via `src/theme.{js,json,ts}`
- [ ] `gatsby-plugin-theme-ui`: support for presets via `gatsby-config.js`
- [ ] Scope all [configuration options](https://theme-ui.com/theming#configuration-flags) to `theme.config`
- [ ] Improve `prefers-color-scheme` media query support – allow color mode to be determined by media query without storing in `localStorage`. See #624, #787
- [ ] Support for CSS Logical Properties #794
- [ ] **Idea:** Simpler API for using presets
- [ ] **Idea:** Provide some solution for self-referencing scales in other scale definitions
- [ ] **Idea:** Plain object syntax responsive values using a `media` key. e.g. `media: { small: { fontSize: 3 } }`
- [ ] **Idea:** Nested property shorthands `font: { size: 3, weight: 'bold' }` [example branch](https://github.com/system-ui/theme-ui/compare/css-shorthands?expand=1)
- [ ] **Idea:** Universal `variant` prop, see #800
- [ ] **Idea:** Merge variants before parsing responsive arrays. This should allow responsive values defined in e.g. `theme.styles` to be overridden with non-responsive values with the `sx` prop. Related #720, #43

**Comment by gausie** [comment]
@hasparus out of interest, why did you unpin this issue?

**Comment by hasparus** [comment]
> @hasparus out of interest, why did you unpin this issue?

By accident. Thank you. Let's keep this one pinned.

**Comment by LekoArts** [comment]
Reading https://github.com/system-ui/theme-ui/issues/2330 - I think another breaking change could be to remove the `MDXProvider` from the `gatsby-plugin-theme-ui`. We've overhauled `gatsby-plugin-mdx` and it's more "barebones" to the other MDX implementations, so people using MDX are already expected to have a `MDXProvider`
